### ISSUE TITLE
subprocess.Popen().stdout is undefined on Windows.

### ISSUE THREAD

**Issue by EpicLPer** [endevrr/AutoRclone-Rewrite#11]
Getting the following error when trying to move files from a local drive to GDrive:

```
C:\rclone\AutoRclone-Rewrite>python autorclone.py --move -sp "C:\Users\epicl\Desktop\Testdir" -d 0AKxxxxxxxxSUk9PVA
[2021-08-25 06:55:03] [AutoRClone] (untitled) [INFO] RClone detected: True
[2021-08-25 06:55:03] [AutoRClone] (untitled) [INFO] Generating RClone config file...
[2021-08-25 06:55:03] [AutoRClone] (untitled) [INFO] Starting job: untitled, at 08:55:03
[2021-08-25 06:55:03] [AutoRClone] (untitled) [INFO] Source: C:\Users\epicl\Desktop\Testdir
[2021-08-25 06:55:03] [AutoRClone] (untitled) [INFO] Destination: 0AKxxxxxxxxSUk9PVA
[2021-08-25 06:55:03] [AutoRClone] (untitled) [INFO] AutoRClone Log: logs/AutoRClone.log
[2021-08-25 06:55:03] [AutoRClone] (untitled) [INFO] RClone Log: logs/rclone.log
[2021-08-25 06:55:03] [AutoRClone] (untitled) [INFO] Calculating source size, please wait
Traceback (most recent call last):
  File "C:\rclone\AutoRclone-Rewrite\autorclone.py", line 324, in <module>
    main()
  File "C:\rclone\AutoRclone-Rewrite\autorclone.py", line 137, in main
    amount_to_transfer_bytes = int(helpers.calculate_path_size(rclone_generated_config_path, src_label, dst_label, action))
TypeError: int() argument must be a string, a bytes-like object or a number, not 'NoneType'
```

The log file shows the same as the above, just without the Python error.  
Is this possible related to #9 ?

**Comment by herodev1337** [comment]
Maybe the error gets thrown because it's a local directory. Can you try to copy from a GDrive to a GDrive and see if its works? If yes, it's possible that I have to change something in the code so it can calculate the size for local directories

**Comment by EpicLPer** [comment]
Seems like I'm getting the same error message still when trying this:

```
C:\rclone\AutoRclone-Rewrite>python autorclone.py --move -s 0AKGxxxxxx9PVA -sp Testdir1 -d 0AKGxxxxxx9PVA -dp Testdir2
[2021-08-25 09:43:48] [AutoRClone] (untitled) [INFO] RClone detected: True
[2021-08-25 09:43:48] [AutoRClone] (untitled) [INFO] Generating RClone config file...
[2021-08-25 09:43:48] [AutoRClone] (untitled) [INFO] Starting job: untitled, at 11:43:48
[2021-08-25 09:43:48] [AutoRClone] (untitled) [INFO] Source: 0AKGxxxxxx9PVA:Testdir1
[2021-08-25 09:43:48] [AutoRClone] (untitled) [INFO] Destination: 0AKGxxxxxx9PVA:Testdir2
[2021-08-25 09:43:48] [AutoRClone] (untitled) [INFO] AutoRClone Log: logs/AutoRClone.log
[2021-08-25 09:43:48] [AutoRClone] (untitled) [INFO] RClone Log: logs/rclone.log
[2021-08-25 09:43:48] [AutoRClone] (untitled) [INFO] Calculating source size, please wait
Traceback (most recent call last):
  File "C:\rclone\AutoRclone-Rewrite\autorclone.py", line 324, in <module>
    main()
  File "C:\rclone\AutoRclone-Rewrite\autorclone.py", line 137, in main
    amount_to_transfer_bytes = int(helpers.calculate_path_size(rclone_generated_config_path, src_label, dst_label, action))
TypeError: int() argument must be a string, a bytes-like object or a number, not 'NoneType'
```

**Comment by herodev1337** [comment]
What happens when you run "rclone move --dry-run DST: SRC:"? Could you post the output

**Comment by williamjohnstone** [comment]
Just as a quick check, you are on the latest version right? @EpicLPer

**Comment by EpicLPer** [comment]
> What happens when you run "rclone move --dry-run DST: SRC:"? Could you post the output

Getting the exact same result when adding `--dry-run` into my used command.

---

> Just as a quick check, you are on the latest version right? @EpicLPer

Yes, latest available Repo clone.

**Comment by williamjohnstone** [comment]
Hmm, I'm having trouble reproducing, please ensure your rclone is up to date, and accessible via the command line, you can run `rclone --version` to check, there used to be a check inside AutoRclone that would check for the presence of rclone, I will create an issue to reimplement this check. If `rclone --version` runs successfully please send the output here.

**Comment by herodev1337** [comment]
> Hmm, I'm having trouble reproducing, please ensure your rclone is up to date, and accessible via the command line, you can run `rclone --version` to check, there used to be a check inside AutoRclone that would check for the presence of rclone, I will create an issue to reimplement this check. If `rclone --version` runs successfully please send the output here.

Same on my side

**Comment by EpicLPer** [comment]
> Hmm, I'm having trouble reproducing, please ensure your rclone is up to date, and accessible via the command line, you can run `rclone --version` to check, there used to be a check inside AutoRclone that would check for the presence of rclone, I will create an issue to reimplement this check. If `rclone --version` runs successfully please send the output here.

```
C:\Users\epicl>rclone --version
rclone v1.56.0
- os/version: Microsoft Windows 10 Pro 2009 (64 bit)
- os/kernel: 10.0.19043.1165 (x86_64)
- os/type: windows
- os/arch: amd64
- go/version: go1.16.5
- go/linking: dynamic
- go/tags: cmount
```

Tho weird enough Win10 2009 isn't the right one, I'm using 21H1.

**Comment by williamjohnstone** [comment]
> > Hmm, I'm having trouble reproducing, please ensure your rclone is up to date, and accessible via the command line, you can run `rclone --version` to check, there used to be a check inside AutoRclone that would check for the presence of rclone, I will create an issue to reimplement this check. If `rclone --version` runs successfully please send the output here.
> 
> ```
> C:\Users\epicl>rclone --version
> rclone v1.56.0
> - os/version: Microsoft Windows 10 Pro 2009 (64 bit)
> - os/kernel: 10.0.19043.1165 (x86_64)
> - os/type: windows
> - os/arch: amd64
> - go/version: go1.16.5
> - go/linking: dynamic
> - go/tags: cmount
> ```
> 
> Tho weird enough Win10 2009 isn't the right one, I'm using 21H1.

Ok rclone is working as it should, do your service accounts have access to the team drive you are trying to copy to?

**Comment by EpicLPer** [comment]
I've simply copied all services accounts from the normal AutoRClone version over, they work on the normal AutoRClone just fine. And yeah I did add all of them to the Team Drive.

**Comment by williamjohnstone** [comment]
Right, one more check then, navigate to your AutoRclone-Rewrite folder, you should see a file called `rclone-generated.conf` if you do, run this command `rclone --config rclone-generate.conf ls dst001:/` this will just list the files in what should be your team drive, and it will rule out any issues with rclone or google.

**Comment by EpicLPer** [comment]
Yep, works just fine and I'm seeing the right Team Drive too.
```
C:\rclone\AutoRclone-Rewrite>rclone --config rclone-generated.conf ls dst001:/
        8 Testdir1/Testfile.txt
        8 Testdir2/Kopie von Testfile.txt
```

**Comment by williamjohnstone** [comment]
Ok rclone is working correctly, as well as the service accounts. can you run `rclone --config rclone-generated.conf move --dry-run  "C:\Users\epicl\Desktop\Testdir" dst001:/` you should see an output something like this at the end, can you post this. 

```2021/08/29 16:01:37 NOTICE:
Transferred:        1.033Gi / 1.033 GiByte, 100%, 869.667 MiByte/s, ETA 0s
Transferred:        10356 / 10356, 100%
Elapsed time:         1.4s
```

**Comment by EpicLPer** [comment]
Yeah, working perfectly, hm...
```
C:\rclone\AutoRclone-Rewrite>rclone --config rclone-generated.conf move --dry-run "C:\Users\epicl\Desktop\Testdir" dst001:/
2021/08/29 17:05:58 NOTICE: Testfile.txt: Skipped move as --dry-run is set (size 0)
2021/08/29 17:05:58 NOTICE:
Transferred:              0 / 0 Byte, -, 0 Byte/s, ETA -
Checks:                 1 / 1, 100%
Renamed:                1
Elapsed time:         0.5s
```

**Comment by williamjohnstone** [comment]
I think the issue might actually be that the file is empty, obviously this needs to be fixed in AutoRclone, as you can see on my output I have a unit after both the 1st and 2nd number, whereas you only have it after the second, to confirm this can you try your original command but try and move a directory which has some data in it, doesn't have to be much just more than 0.

**Comment by EpicLPer** [comment]
I tried the same with a file that actually does have some contents in it (a JPG file) and AutoRClone still gives me the same result:
```
C:\rclone\AutoRclone-Rewrite>autorclone.py --move -sp "C:\Users\epicl\Desktop\Testdir" -d 0AxxxxxxVA
[2021-08-29 15:09:34] [AutoRClone] (untitled) [INFO] RClone detected: True
[2021-08-29 15:09:34] [AutoRClone] (untitled) [INFO] Generating RClone config file...
[2021-08-29 15:09:34] [AutoRClone] (untitled) [INFO] Starting job: untitled, at 17:09:34
[2021-08-29 15:09:34] [AutoRClone] (untitled) [INFO] Source: C:\Users\epicl\Desktop\Testdir
[2021-08-29 15:09:34] [AutoRClone] (untitled) [INFO] Destination: 0AxxxxxxVA
[2021-08-29 15:09:34] [AutoRClone] (untitled) [INFO] AutoRClone Log: logs/AutoRClone.log
[2021-08-29 15:09:34] [AutoRClone] (untitled) [INFO] RClone Log: logs/rclone.log
[2021-08-29 15:09:34] [AutoRClone] (untitled) [INFO] Calculating source size, please wait
Traceback (most recent call last):
  File "C:\rclone\AutoRclone-Rewrite\autorclone.py", line 324, in <module>
    main()
  File "C:\rclone\AutoRclone-Rewrite\autorclone.py", line 137, in main
    amount_to_transfer_bytes = int(helpers.calculate_path_size(rclone_generated_config_path, src_label, dst_label, action))
TypeError: int() argument must be a string, a bytes-like object or a number, not 'NoneType'
```
... whereas rclone gives me the following

```
C:\rclone\AutoRclone-Rewrite>rclone -v --config rclone-generated.conf move "C:\Users\epicl\Desktop\Testdir" dst001:/
2021/08/29 17:12:02 INFO  : background.jpg: Copied (new)
2021/08/29 17:12:02 INFO  : background.jpg: Deleted
2021/08/29 17:12:02 INFO  :
Transferred:        3.585Mi / 3.585 MiByte, 100%, 3.581 MiByte/s, ETA 0s
Checks:                 2 / 2, 100%
Deleted:                1 (files), 0 (dirs)
Renamed:                1
Transferred:            1 / 1, 100%
Elapsed time:         2.5s
```
... and just in case here's the dry-run command from earlier again and with a file that has contents
```
C:\rclone\AutoRclone-Rewrite>rclone -v --dry-run --config rclone-generated.conf move "C:\Users\epicl\Desktop\Testdir" dst001:/
2021/08/29 17:12:44 NOTICE: background.jpg: Skipped delete as --dry-run is set (size 3.585Mi)
2021/08/29 17:12:44 INFO  : There was nothing to transfer
2021/08/29 17:12:44 NOTICE:
Transferred:              0 / 0 Byte, -, 0 Byte/s, ETA -
Checks:                 2 / 2, 100%
Deleted:                1 (files), 0 (dirs)
Elapsed time:         0.5s
```

**Comment by williamjohnstone** [comment]
I've just notice that it seems to be trying to read stderr rather than stdout, this may be the issue, give me two seconds I will commit a change.

**Comment by williamjohnstone** [comment]
Ok I've pushed the change, if you pull the latest changes and try again, it should work as normal, if you get a size it's working correctly, if it can't it will return 0 and you will see that it says your source size is 0 Bytes, if it does say 0 Bytes please let me know, but you should now be able to use AutoRclone although the ETA may be wrong if it can't read the source size.

**Comment by EpicLPer** [comment]
Getting a slightly different error now:
```
Traceback (most recent call last):
  File "C:\rclone\AutoRclone-Rewrite\autorclone.py", line 324, in <module>
    main()
  File "C:\rclone\AutoRclone-Rewrite\autorclone.py", line 137, in main
    amount_to_transfer_bytes = int(helpers.calculate_path_size(rclone_generated_config_path, src_label, dst_label, action))
  File "C:\rclone\AutoRclone-Rewrite\util\helpers.py", line 48, in calculate_path_size
    for line in process.stdout:
TypeError: 'NoneType' object is not iterable
```

**Comment by williamjohnstone** [comment]
Ok so it's still having issues capturing rclone output, this will need to be resolved, but for the time being I'll push a temporary fix.

**Comment by williamjohnstone** [comment]
Try now

**Comment by EpicLPer** [comment]
Yeah it seems to "work" now, however reports a size of 0 and fails to contact RClone, thus tries to use different service accounts. However, in the background, the move option already finished before the first retrying-message even popped up.
```
C:\rclone\AutoRclone-Rewrite>autorclone.py --move -sp "C:\Users\epicl\Desktop\Testdir" -d 0AKxxxxxx9PVA
[2021-08-29 15:36:29] [AutoRClone] (untitled) [INFO] RClone detected: True
[2021-08-29 15:36:29] [AutoRClone] (untitled) [INFO] Generating RClone config file...
[2021-08-29 15:36:29] [AutoRClone] (untitled) [INFO] Starting job: untitled, at 17:36:29
[2021-08-29 15:36:29] [AutoRClone] (untitled) [INFO] Source: C:\Users\epicl\Desktop\Testdir
[2021-08-29 15:36:29] [AutoRClone] (untitled) [INFO] Destination: 0AKxxxxxx9PVA
[2021-08-29 15:36:29] [AutoRClone] (untitled) [INFO] AutoRClone Log: logs/AutoRClone.log
[2021-08-29 15:36:29] [AutoRClone] (untitled) [INFO] RClone Log: logs/rclone.log
[2021-08-29 15:36:29] [AutoRClone] (untitled) [INFO] Calculating source size, please wait
[2021-08-29 15:36:29] [AutoRClone] (untitled) [INFO] Source size: 0 Bytes
[2021-08-29 15:36:49] [AutoRClone] (untitled) [INFO] Encountered 3 successive errors when trying to contact rclone, switching accounts (1.0/3)
[2021-08-29 15:37:09] [AutoRClone] (untitled) [INFO] Encountered 3 successive errors when trying to contact rclone, switching accounts (2.0/3)
[2021-08-29 15:37:29] [AutoRClone] (untitled) [INFO] Job FINISHED (this message will be better soon)
```

**Comment by williamjohnstone** [comment]
Yup, that seems correct, once rclone is finished it will exit, autorclone has no way of knowing if rclone exited because of an error, or if it was finished it's operation which is why it switches to a new service account. the 0 Bytes issue will need to be fixed but other than that it seems to be working, I would now invite you to try with some larger files just to ensure it is working, as small files don't give a great indication if everything is working.

**Comment by EpicLPer** [comment]
Been moving about 6GB now and it seems to work, same output as before tho. The ETA was calculated with 1 hour since it reported x GB left of 0 GB.

**Comment by williamjohnstone** [comment]
Yes that is to be expected until source sizing is fixed. Thanks for your help debugging.

**Comment by herodev1337** [comment]
> I've just notice that it seems to be trying to read stderr rather than stdout, this may be the issue, give me two seconds I will commit a change.

I tested it and it only gave me an output on the stderr. The stdout was just an empty. Thought it was an rclone bug

**Comment by williamjohnstone** [comment]
I see, well It will need to be tested to ensure it works across all platforms.
