### ISSUE TITLE
UnboundLocalError: local variable 'new_remote' referenced before assignment

### ISSUE THREAD

**Issue by ghost** [endevrr/AutoRclone-Rewrite#3]
I have this error on mi terminal/ help me
   AutoRclone-Rewrite-master python3 autorclone.py --copy -s 0AJzqsF09gQFUk9PVA -d 0AAhUBIpmAKGUk9PVA --rclone-config-path /home/avi/.config/rclone/rclone.conf
[2021-07-13 22:03:13] [AutoRClone] (untitled) [INFO] RClone detected: True
[2021-07-13 22:03:13] [AutoRClone] (untitled) [INFO] Generating RClone config file...
Traceback (most recent call last):
  File "/home/avi/Downloads/AutoRclone-Rewrite-master/autorclone.py", line 304, in <module>
    main()
  File "/home/avi/Downloads/AutoRclone-Rewrite-master/autorclone.py", line 88, in main
    end_id, src_is_crypt, dst_is_crypt = config_gen.gen_rclone_cfg(args, rclone_generated_config_path)
  File "/home/avi/Downloads/AutoRclone-Rewrite-master/util/config_gen.py", line 101, in gen_rclone_cfg
    parsed_config = config_parser.parse_config(args.rclone_config_path)
  File "/home/avi/Downloads/AutoRclone-Rewrite-master/util/config_parser.py", line 99, in parse_config
    remotes.append(new_remote)
UnboundLocalError: local variable 'new_remote' referenced before assignment

**Comment by ghost** [comment]
the solution is>
rclone config
when ask if is a team drive select yes, add the two team drives and for check the path of config put
rclone config file


python3 autorclone.py --copy -s 0AJzqsF092gQFU9PVA -d 0AAhUBIpmAKGUk9PVA --rclone-config-path /root/.config/rclone/rclone.conf

**Comment by williamjohnstone** [comment]
Thanks for reporting, If anyone wants to push a fix for this, should be straight forward, I should get around to it eventually, but I'm on a busy schedule at the moment
