### ISSUE TITLE
Regarding ValueError: could not convert string to float: '3614614213686 bytes)'

### ISSUE THREAD

**Issue by sai5567** [endevrr/AutoRclone-Rewrite#6]
Hi im getting this error on mac os and android too i dont know why 

can you help

Last login: Sat Aug  7 10:29:52 on ttys000
[2021-08-07 05:03:01] [AutoRClone] (untitled) [INFO] RClone detected: True
[2021-08-07 05:03:01] [AutoRClone] (untitled) [INFO] Generating RClone config file...
[2021-08-07 05:03:01] [AutoRClone] (untitled) [INFO] Starting job: untitled, at 10:33:01
[2021-08-07 05:03:01] [AutoRClone] (untitled) [INFO] Source: 0ALMM_AQHddKgUk9PVA
[2021-08-07 05:03:01] [AutoRClone] (untitled) [INFO] AutoRClone Log: logs/AutoRClone.log
[2021-08-07 05:03:01] [AutoRClone] (untitled) [INFO] RClone Log: logs/rclone.log
[2021-08-07 05:03:01] [AutoRClone] (untitled) [INFO] Calculating source size, please wait
Traceback (most recent call last):
  File "autorclone.py", line 307, in <module>
    main()
  File "autorclone.py", line 129, in main
    amount_to_transfer = helpers.convert_bytes_to_best_unit(amount_to_transfer_bytes)
  File "/Users/sai/Downloads/AutoRclone-Rewrite-master/util/helpers.py", line 32, in convert_bytes_to_best_unit
    bytes_value = float(bytes_value)
ValueError: could not convert string to float: '3614614213686 bytes)'
sai@Sais-MacBook-Pro AutoRclone-Rewrite-master %

**Comment by herodev1337** [comment]
I'll have a fix ready. Pushing it soon

**Comment by sai5567** [comment]
Hi i changed some lines of code mentioned in the pull requests and im getting this error

File "autorclone.py", line 307, in <module>
    main()
  File "autorclone.py", line 128, in main
    amount_to_transfer_bytes = int(helpers.calculate_path_size(src_label, rclone_generated_config_path)) - int(helpers.calculate_path_size(dst_label, rclone_generated_config_path))            
ValueError: invalid literal for int() with base 10: '10985893441110 bytes)'

**Comment by endevrr** [comment]
@herodev1337 Seems you are just casting the string as an int which still doesn't work, I will take a look at the helper function itself as it should only be returning an int anyway

**Comment by herodev1337** [comment]
@endevrr I encountered the same bug and fixed it already. Forgot to push the file. There was a typo in the helper file

**Comment by endevrr** [comment]
Right thanks, I'll merge now

**Comment by endevrr** [comment]
closed by #7

**Comment by endevrr** [comment]
This issue was introduced by an rclone update, where Bytes was changed to bytes I will add a fix to ensure AutoRclone is backwards compatible
