### ISSUE TITLE
TypeError: can only concatenate str (not "NoneType") to str

### ISSUE THREAD

**Issue by williamjohnstone** [endevrr/AutoRclone-Rewrite#8]
```
axxbxx@CCCP:/opt/AutoRclone-Rewrite-orig$ python3 autorclone.py --sync -s gcd-admin-rfid -sp 4KTV -d gcd-crypt -dp media/plex/4KTV --rclone-config-path /home/axxbxx/.config/rclone/rclone2.conf --drive-chunk-size 64M --transfers 8 --dry-run
[2021-08-07 08:04:13] [AutoRClone] (untitled) [INFO] RClone detected: True
[2021-08-07 08:04:13] [AutoRClone] (untitled) [INFO] Generating RClone config file...
Traceback (most recent call last):
  File "/opt/AutoRclone-Rewrite-orig/autorclone.py", line 307, in <module>
    main()
  File "/opt/AutoRclone-Rewrite-orig/autorclone.py", line 88, in main
    end_id, src_is_crypt, dst_is_crypt = config_gen.gen_rclone_cfg(args, rclone_generated_config_path)
  File "/opt/AutoRclone-Rewrite-orig/util/config_gen.py", line 109, in gen_rclone_cfg
    dest_remote, dst_is_crypt = gen_remote_template(args.destination, parsed_config, args,is_config_file_specified)
  File "/opt/AutoRclone-Rewrite-orig/util/config_gen.py", line 40, in gen_remote_template
    remote_template += '[{}{:03d}_crypt]\n' \
TypeError: can only concatenate str (not "NoneType") to str
```

**Comment by endevrr** [comment]
This issue was introduced by an rclone update, where Bytes was changed to bytes I will add a fix to ensure AutoRclone is backwards compatible

**Comment by williamjohnstone** [comment]
Fixed, please update to the latest version
